/**
 * Writes supabase/seed_shop_products.sql from FALLBACK_PRODUCTS.
 * Run from repo root: npx tsx scripts/generate-shop-seed.ts [--dry-run] [--out <path>]
 */
import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { FALLBACK_PRODUCTS } from "../src/data/products.fallback";

const __dirname = dirname(fileURLToPath(import.meta.url));

const DEFAULT_OUT = join(__dirname, "../supabase/seed_shop_products.sql");

function printHelp(): void {
  console.log(`generate-shop-seed — emit SQL seed for shop_products from FALLBACK_PRODUCTS

Usage:
  npx tsx scripts/generate-shop-seed.ts [options]

Options:
  --out <path>   Output file (default: supabase/seed_shop_products.sql)
  --dry-run      Print path and size; do not write
  -h, --help     Show this message

Examples:
  npx tsx scripts/generate-shop-seed.ts
  npx tsx scripts/generate-shop-seed.ts --dry-run
  npx tsx scripts/generate-shop-seed.ts --out /tmp/seed_shop_products.sql
`);
}

function parseArgs(argv: string[]): {
  help: boolean;
  dryRun: boolean;
  outPath: string;
} {
  const rest = argv.filter((a) => a !== "--");
  let dryRun = false;
  let help = false;
  let outPath = DEFAULT_OUT;
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i];
    if (a === "-h" || a === "--help") {
      help = true;
      continue;
    }
    if (a === "--dry-run") {
      dryRun = true;
      continue;
    }
    if (a === "--out") {
      const next = rest[i + 1];
      if (!next || next.startsWith("-")) {
        console.error(`Error: --out requires a path.
  npx tsx scripts/generate-shop-seed.ts --out supabase/seed_shop_products.sql`);
        process.exit(2);
      }
      outPath = resolve(process.cwd(), next);
      i++;
      continue;
    }
    if (a.startsWith("-")) {
      console.error(`Error: unknown option "${a}".
  npx tsx scripts/generate-shop-seed.ts --help`);
      process.exit(2);
    }
    console.error(`Error: unexpected argument "${a}".
  npx tsx scripts/generate-shop-seed.ts --help`);
    process.exit(2);
  }
  return { help, dryRun, outPath };
}

function jsonbLiteral(obj: unknown): string {
  const s = JSON.stringify(obj);
  return `'${s.replace(/'/g, "''")}'::jsonb`;
}

function buildSql(): string {
  const rows = FALLBACK_PRODUCTS.map((p, i) => {
    return `  (${p.id}, ${jsonbLiteral(p)}, ${i + 1}, true)`;
  });

  return `-- Generated by scripts/generate-shop-seed.ts — do not edit by hand.
-- Run in Supabase SQL editor after applying migrations.

insert into public.shop_products (id, body, sort_order, is_published)
values
${rows.join(",\n")}
on conflict (id) do update set
  body = excluded.body,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
`;
}

const { help, dryRun, outPath } = parseArgs(process.argv.slice(2));
if (help) {
  printHelp();
  process.exit(0);
}

const sql = buildSql();

if (dryRun) {
  const bytes = Buffer.byteLength(sql, "utf8");
  console.log(`dry-run: would write ${bytes} bytes to ${outPath}`);
  process.exit(0);
}

writeFileSync(outPath, sql, "utf8");
console.log(`wrote: ${outPath}`);
console.log(`rows: ${FALLBACK_PRODUCTS.length}`);
